os: Visual Studio 2015
build: off

install:
  - ps: wget https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_windows_amd64.zip -OutFile consul.zip
  - cmd: 7z x consul.zip -o"C:\Consul" -y > nul
  - ps: $MyProcess = Start-Process C:\Consul\consul.exe -ArgumentList "agent -dev" -PassThru

before_test:
  - dotnet --info
  - dotnet restore

test_script:
  # Build sample
  - dotnet test test/CondenserTests
  - dotnet test test/Condenser.Tests.Integration
  
after_test:
  # Build and pack source
  - dotnet pack -c Release src/CondenserDotNet.Client --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/CondenserDotNet.Host --version-suffix %APPVEYOR_BUILD_NUMBER%

artifacts:
  path: '**/*.nupkg'

deploy:  
- provider: NuGet
  server: https://www.myget.org/F/condenserdotnet/api/v2/package
  api_key:
    secure: 5mBb0A2rlwk1Iq6FEo94XSORm9etc3xPn0oLZ8dIJ6Hmm1G7quqf+Bz6fm+ft+FK
  skip_symbols: true
  on:
    branch: master